# Generated by Django 6.1.1 on 2026-09-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='section',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids'), ('Unisex', 'Unisex')], default='Unisex', max_length=20),
        ),
    ]
